version: '3.3'

services:
  todo-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env  # Cargamos el archivo .env

  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Aquí se define el volumen para la persistencia

volumes:
  pgdata: {}  # Declaramos el volumen vacío para que Docker lo maneje



